// scenes/protopirate_scene_protocol_help.c
// In-app protocol documentation by brand + quick usage guide
#include "../protopirate_app_i.h"

#define TAG "ProtoPirateProtoHelp"

static const char* help_text =
    "=== QUICK START ===\n"
    "\n"
    "1. RECEIVE\n"
    "  Pick freq, point at keyfob.\n"
    "  Press OK to lock signal.\n"
    "\n"
    "2. SAVED CAPTURES\n"
    "  View decoded signals.\n"
    "\n"
    "3. SUB DECODE\n"
    "  Load .sub files from SD.\n"
    "\n"
    "4. CONFIG\n"
    "  Freq, hopping, TX power,\n"
    "  auto-save, emulate toggle.\n"
    "\n"
    "5. TIMING TUNER\n"
    "  Compare fob timing.\n"
    "\n"
    "=== FORD ===\n"
    "\n"
    "V0 [AM 315/433]\n"
    "  Manchester, Rolling Code,\n"
    "  CRC matrix GF(2)\n"
    "  Decode+Encode\n"
    "\n"
    "V1 [FM 315/433]\n"
    "  Manchester, Rolling Code,\n"
    "  CRC16. Decode+Encode\n"
    "\n"
    "V2 [FM 434]\n"
    "  Manchester, Replay.\n"
    "  Decode+Encode\n"
    "\n"
    "V3 [AM/FM 434]\n"
    "  Manchester, Rolling Code.\n"
    "  Decode only\n"
    "\n"
    "=== KIA ===\n"
    "\n"
    "V0 [FM 315/433]\n"
    "  PWM, Rolling Code, CRC8\n"
    "\n"
    "V1 [AM 315/433]\n"
    "  Manchester, Rolling Code,\n"
    "  CRC4\n"
    "\n"
    "V2 [FM 315/433]\n"
    "  Manchester, Rolling Code,\n"
    "  CRC4\n"
    "\n"
    "V3/V4 [FM 315/433]\n"
    "  PWM, KeeLoq, CRC4\n"
    "\n"
    "V5 [FM 315/433]\n"
    "  PWM, Rolling Code\n"
    "\n"
    "V6 [FM 315/433]\n"
    "  Manchester, AES-128,\n"
    "  CRC8\n"
    "\n"
    "V7 [FM 315/433]\n"
    "  Manchester, Rolling Code,\n"
    "  CRC8\n"
    "\n"
    "=== VAG ===\n"
    "(VW/Audi/Seat/Skoda)\n"
    "\n"
    "[AM 434.42]\n"
    "  Manchester\n"
    "  Crypto: AUT64 + XTEA\n"
    "  Decode+Encode\n"
    "\n"
    "=== PSA ===\n"
    "(Peugeot/Citroen)\n"
    "\n"
    "[AM+FM 315/433]\n"
    "  Manchester\n"
    "  Crypto: XTEA+XOR, CRC8\n"
    "  Decode+Encode\n"
    "  Brute-force plugin avail.\n"
    "\n"
    "=== FIAT ===\n"
    "\n"
    "V0 [AM 315/433]\n"
    "  Manchester, Rolling Code\n"
    "  (static emulate only)\n"
    "\n"
    "V1 [AM 315/433]\n"
    "  Manchester, HITAG2,\n"
    "  XOR8. Needs key prompt\n"
    "\n"
    "V2 [AM 315/433]\n"
    "  Manchester, Rolling Code.\n"
    "  Decode only\n"
    "\n"
    "=== HONDA ===\n"
    "\n"
    "Static [FM 315/433]\n"
    "  PWM, Static code,\n"
    "  Checksum\n"
    "\n"
    "V1 [AM 315/433]\n"
    "  Manchester, Rolling Code,\n"
    "  CRC4\n"
    "\n"
    "V2 [FM 315/433]\n"
    "  PWM, Rolling Code,\n"
    "  Check+Tail\n"
    "\n"
    "=== OTHER ===\n"
    "\n"
    "Chrysler V0 [AM 315/433]\n"
    "  PWM, Rolling Code\n"
    "\n"
    "Mazda V0 [AM+FM 315/433]\n"
    "  Manchester, Rolling Code,\n"
    "  Checksum\n"
    "\n"
    "Mitsubishi V0 [FM 315/433]\n"
    "  PWM, Rolling Code\n"
    "\n"
    "Porsche Touareg [AM 315]\n"
    "  PWM, Rolling Code\n"
    "\n"
    "Renault V0 [AM 315/433]\n"
    "  Manchester, Rolling/Replay\n"
    "\n"
    "Subaru [AM 315/433]\n"
    "  PPM, Rolling Code\n"
    "\n"
    "Scher-Khan [FM]\n"
    "  PWM, Magic Code\n"
    "\n"
    "StarLine [AM 315/433]\n"
    "  PWM, KeeLoq\n"
    "\n"
    "=== CREDITS ===\n"
    "\n"
    "ProtoPirate by The Pirates'\n"
    "Plunder. Fork by Carlitack.\n"
    "Protocabrax v1.0\n"
    "Compiled with FlipperFAP\n"
    "joelewis012.github.io\n";

void protopirate_scene_protocol_help_on_enter(void* context) {
    furi_check(context);
    ProtoPirateApp* app = context;

    if(!protopirate_ensure_widget(app)) {
        FURI_LOG_E(TAG, "Failed to allocate widget");
        notification_message(app->notifications, &sequence_error);
        scene_manager_previous_scene(app->scene_manager);
        return;
    }

    widget_reset(app->widget);
    widget_add_text_scroll_element(app->widget, 0, 0, 128, 64, help_text);
    view_dispatcher_switch_to_view(app->view_dispatcher, ProtoPirateViewWidget);
}

bool protopirate_scene_protocol_help_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}

void protopirate_scene_protocol_help_on_exit(void* context) {
    furi_check(context);
    ProtoPirateApp* app = context;
    widget_reset(app->widget);
}
